- name: Append prod-release checklist
  uses: actions/github-script@v7
  with:
    script: |
      // core, github, context are already available
      const fs = require('fs');

      const CHECKLIST_PATH = '.github/PULL_REQUEST_TEMPLATE/prod_release_checklist.md';

      // read the checklist file
      if (!fs.existsSync(CHECKLIST_PATH)) {
        core.warning(`Checklist not found at ${CHECKLIST_PATH}; nothing to append.`);
        return;
      }
      const checklist = fs.readFileSync(CHECKLIST_PATH, 'utf8').trim();

      // current PR body
      const pr   = context.payload.pull_request;
      const body = pr.body || '';

      // avoid duplicates
      if (body.includes(checklist)) {
        core.info('Checklist already present – skipping.');
        return;
      }

      // append checklist
      const newBody = `${body}\n\n---\n${checklist}`;

      await github.rest.pulls.update({
        owner: context.repo.owner,
        repo:  context.repo.repo,
        pull_number: pr.number,
        body: newBody
      });
