# .github/workflows/prod-release-template.yml
name: Inject prod-release PR template

on:
  pull_request:
    # Trigger whenever a PR targets the master branch
    branches: [ master ]
    types: [opened, edited, ready_for_review]

jobs:
  inject:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Load template & update PR body
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const template = fs.readFileSync(
              '.github/PULL_REQUEST_TEMPLATE/prod_release.md',
              'utf8'
            );

            const existing = context.payload.pull_request.body || '';
            // Prepend the template, keep author text below a divider
            const body = `${template}\n\n---\n${existing}`;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body
            });
